In [2]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [24]:
X,y = make_regression(n_samples = 100,n_features = 2,n_informative = 2,n_targets =1,noise = 50)

In [25]:
# Feature column
X

array([[-5.30164842e-01, -8.99937813e-01],
       [-1.30854135e+00, -3.34575324e-01],
       [-1.25717718e+00, -6.89882320e-01],
       [-4.04100451e-01,  3.54673414e-01],
       [ 4.44626610e-01,  4.41108112e-01],
       [ 1.06013935e+00,  1.40190284e+00],
       [ 1.59457832e+00,  1.75330281e-03],
       [ 9.52520134e-01, -8.16080250e-01],
       [ 1.16153063e+00,  1.07092298e+00],
       [-5.01389588e-01, -3.79282217e-01],
       [-1.26517671e+00, -4.87228246e-01],
       [-5.68686181e-01,  1.39626278e+00],
       [-2.35719557e+00, -1.19306825e+00],
       [ 2.26893969e+00, -7.89157246e-01],
       [ 6.50596635e-01, -7.81481487e-01],
       [ 1.99865382e+00,  2.48283316e-01],
       [ 3.86625014e-01,  4.34695136e-01],
       [-1.10935745e+00, -6.64147986e-01],
       [ 4.26219267e-01, -2.39119889e+00],
       [-9.65718281e-02, -8.88576562e-01],
       [-6.36366536e-01, -1.23349014e+00],
       [-7.86146944e-01,  9.68018787e-02],
       [ 1.37345725e-01, -6.70646508e-02],
       [-1.

In [26]:
#Target column
y

array([ -84.61038833, -112.34372669, -181.98916265,   -7.66046026,
         -1.65187145,   91.75180548,   62.89871787,   12.86980095,
        116.49952535,   -2.90225584, -142.22543229,   -2.99168762,
       -170.90676397,  123.82358613,  -16.67171515,   78.06117853,
         69.50504932,  -63.88826654,  -54.90713656,  -13.43973186,
          6.23810524,  -70.99946087,   17.51824176,  -67.91583945,
       -117.63286538,   23.04946388,  100.85463325,  -85.25397363,
       -124.24493989,  -42.11436668,   45.81296588,   -3.50997023,
        -78.14434734,   21.01928349,  -89.12703019,   88.74765834,
        131.65708089,  -64.19641454, -100.88063551, -130.03561709,
        -15.20568688,   79.73534041,   19.03511379,  -33.5162856 ,
        -51.3449432 ,   33.70642378,   64.12688155,   34.99007104,
         55.54436802,   80.11944681,  161.66172184,   70.10487918,
         66.45071278, -165.63104872,   68.18780738,   48.02726482,
        -88.4914771 ,   33.31111522,   37.0035452 , -129.40323

In [27]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [28]:
df.head()

feature1  feature2      target
0 -0.530165 -0.899938  -84.610388
1 -1.308541 -0.334575 -112.343727
2 -1.257177 -0.689882 -181.989163
3 -0.404100  0.354673   -7.660460
4  0.444627  0.441108   -1.651871

In [29]:
fig = px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 3)

In [31]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [32]:
lr.fit(X_train,y_train)

LinearRegression()

In [33]:
y_pred = lr.predict(X_test)

In [ ]:
x = np.linspace(-5,5,10)
y = np.linspace(-5,5,10)
xGrid,yGrid = np.meshgrid(y,x)

z_final = lr.predict((final).reshape(10,10))
z= z_final
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [ ]:
fig = px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.add_trace(go.Surface(x = x,y = y,z =z ))
fig.show()

In [43]:
lr.coef_

array([55.66659268, 41.14807149])

In [44]:
lr.intercept_

1.4950499943605484